services:
  mongodb:
    image: mongo:5
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=artemInd
      - MONGO_INITDB_ROOT_PASSWORD=artemInd
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8086:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=artemInd
      - ME_CONFIG_MONGODB_ADMINPASSWORD=artemInd
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}